config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  get 'homes/about', to: 'homes#about'
  get 'homes/enjoy', to: 'homes#enjoy'
  get 'homes/faq', to: 'homes#faq'
  get 'reservations/:start_date', to: 'reservations#show'
  resources :reservations, expect: [:show]
  resources :horses, expect: [:show]
  resources :menus
  resources :admin_reservations
  resources :news
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/horse.rb
class Horse < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/menu.rb
class Menu < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :reservations
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  validates :menu, presence: true

  def reserved?
    reserved
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations
  enum role: { member: 0, admin: 1}
end

app/controllers/admin_reservations_controller.rb
class AdminReservationsController < ApplicationController
  def new
    @reservation = Reservation.new
    @menus = Menu.all
  end
  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:success] = "Object successfully created"
      redirect_to reservations_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  
  private
  def reservation_params
    params.require(:reservation).permit(:start_time).merge(user_id: '1',menu_id: '1')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @news = News.all
  end

  def about
  end

  def enjoy
  end
  
  def faq
  end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  def new
    @horse = Horse.new
  end

  def create
    @horse = Horse.new(horse_params)
    if @horse.save
      flash[:success] = "horse successfully created"
      redirect_to horses_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  
  def edit
    @horse = Horse.find(params[:id])
  end
  
  def update
    @horse = Horse.find(params[:id])
      if @horse.update(horse_params)
        flash[:success] = "horse was successfully updated"
        redirect_to horses_path
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  def index
    @horses = Horse.all
  end
  
  def destroy
    @horse = Horse.find(params[:id])
    if @horse.destroy
      flash[:success] = 'horse was successfully deleted.'
      redirect_to horses_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to horses_path
    end
  end

  private
  def horse_params
    params.require(:horse).permit(:name, :variety, :sex, :color, :race_name, :birthday, :entry, :memo, :image)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    @menu = Menu.new
  end
  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      flash[:success] = "Object successfully created"
      redirect_to menus_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  def index
    @menus = Menu.all
  end
  def edit
    @menu = Menu.find(params[:id])
  end
  def update
    @menu = Menu.find(params[:id])
      if @menu.update(menu_params)
        flash[:success] = "Object was successfully updated"
        redirect_to menus_path
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  def destroy
    @menu = Menu.find(params[:id])
    if @menu.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to menus_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to menus_path
    end
  end
  
  private
  def menu_params
    params.require(:menu).permit(:title, :money, :time, :memo, :image)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
    @news = News.new
  end
  def create
    @news = News.new(news_params)
    if @news.save
      flash[:success] = "Object successfully created"
      redirect_to @news
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  def show
    @news = News.find(params[:id])
  end
  
  
  private
  def news_params
    params.require(:news).permit(:title, :content)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reservations = Reservation.all
  end

  def show
    from = Date.strptime(params[:start_date], '%Y-%m-%d')
    @reservations = Reservation.where('start_time >= ? and start_time < ?', from, from + 1)
    @p = params
  end
  def new
    @reservation = Reservation.new
    @menus = Menu.all
  end
  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:success] = "予約時間を設定しました"
      redirect_to reservations_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  def edit
    @reservation = Reservation.find(params[:id])
    
  end
  def update
    @reservation = Reservation.find(params[:id])
      if @reservation.update(reservation_params)
        flash[:success] = "予約しました"
        redirect_to reservation_path(@reservation.start_time.strftime("%Y-%m-%d"))
      else
        flash[:alert] = "メニューを選択してください"
        render 'edit', {reservation: @reservation}
      end
  end
  
  private
  def reservation_params
    params.require(:reservation).permit(:menu_id).merge(user_id: current_user.id, reserved: 1)
  end
  def move_to_signed_in
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end

end

app/helpers/admin_reservations_helper.rb
module AdminReservationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/admin_reservations/new.html.erb
<div class="container mw-md">
  <%= form_with model: @reservation, url: {controller: 'admin_reservations', action: 'create'} do |f|%>
    <div class="form-group">
      <label class="control-label">乗馬メニュー</label>
      <%= f.date_field :start_time, class: "form-control" %>
    </div>
    <div class="form-group">
      <label class="control-label">乗馬メニュー</label>
      <%= f.datetime_select :start_time,{include_blank: true, start_hour: 10, end_hour: 15, discard_minute:true}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.submit '登録する', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/homes/index.html.erb
<div class="container">
  <div class="jumbotron p-3 mb-2 bg-light text-success">
    <div class="col-md-12 px-0">
      <h1 class="display-4 font-italic">蓼科乗馬ファームのホームページへようこそ。</h1>
      <p class="lead my-3">今まで乗馬してみたいと思いながらチャンスがなかった方、今現在乗ってはいるのだけれどしっくりこない方、馬のことを知りたい方へサポートできる施設を目指しています。当ファームでは競技思考の乗馬ではなく、実用的な移動手段としての乗馬を広めたく日々取り組んでいます。移動手段としての乗馬は馬場だけで乗るのとは違います。思い通りの速度と方向がコントロール出来ればよいのです。そして馬も人間も快適に動ければよいのです。馬場と違い移動する先々で周りの環境が変化します。新緑や紅葉、自然の中を行く気分爽快の外乗は乗馬の醍醐味の一つではないでしょうか。初めて乗る方も、乗ったことがある方も、また乗り続けている方も楽しく乗っていただけます。乗馬スタイルを超えたどのスタイルにも共通な部分があります。その部分で乗ることが出来れば誰もが楽しい乗馬が可能になります。そして、馬の生態を含めたいろいろなことを理解することが乗馬の楽しさにつながると思います。このサイトから今までにない乗馬や馬の情報を紹介出来ればと思います。</p>
      <p class="lead mb-0"><a href="#" class="text-dark font-weight-bold">Continue reading...</a></p>
    </div>
  </div>
</div>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
<!--      <% @news.each do |new| %>
        <div class="blog-post">
          <h2 class="blog-post-title"><%= link_to new.title, news_path(new) %></h2>
          <p class="blog-post-meta"><%= new.updated_at.strftime('%Y年%m月%d日') %></p>
          <p><%= simple_format(new.content) %></p>
        </div>
      <% end %> -->

      <nav class="blog-pagination">
        <a class="btn btn-outline-primary" href="#">Older</a>
        <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
      </nav>
    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">今まで乗馬してみたいと思いながらチャンスがなかった方、今現在乗ってはいるのだけれどしっくりこない方、馬のことを知りたい方へサポートできる施設を目指しています。当ファームでは競技思考の乗馬ではなく、実用的な移動手段としての乗馬を広めたく日々取り組んでいます。移動手段としての乗馬は馬場だけで乗るのとは違います。思い通りの速度と方向がコントロール出来ればよいのです。そして馬も人間も快適に動ければよいのです。馬場と違い移動する先々で周りの環境が変化します。新緑や紅葉、自然の中を行く気分爽快の外乗は乗馬の醍醐味の一つではないでしょうか。初めて乗る方も、乗ったことがある方も、また乗り続けている方も楽しく乗っていただけます。乗馬スタイルを超えたどのスタイルにも共通な部分があります。その部分で乗ることが出来れば誰もが楽しい乗馬が可能になります。そして、馬の生態を含めたいろいろなことを理解することが乗馬の楽しさにつながると思います。このサイトから今までにない乗馬や馬の情報を紹介出来ればと思います。</p>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->
  </div><!-- /.row -->
</main><!-- /.container -->

<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/horses/edit.html.erb
<div class="container mw-md">
  <%= form_for @horse do |f|%>
    <% if @horse.image? %>
      <%= image_tag @horse.image.url %>
    <% else %>
      <%= image_tag "/assets/default.png", :size => '100x100' %>
    <% end %>
    <div class="form-group">
      <label class="control-label">名前</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">品種</label>
      <%= f.text_field :variety, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">性別</label>
      <%= f.text_field :sex, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">毛色</label>
      <%= f.text_field :color, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">競走馬名号</label>
      <%= f.text_field :race_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">生年月日</label>
      <%= f.date_field :birthday, class: "form-control"%>
    </div>
    <div class="form-group">
      <label  class="control-label">入厩日</label>
      <%= f.date_field :entry, class: "form-control"%>
    </div>
    <div class="form-group">
      <label  class="control-label">所属</label>
      <%= f.text_field :memo, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">写真</label><br>
      <button type="button" class="btn btn-outline-secondary rounded-pill btn-block">
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: 'btn-block'%>
      </button>
    </div>
    <div class="form-group">
      <%= f.submit '更新する', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/horses/index.html.erb
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1>ファームの馬たち</h1>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to '新規追加',new_horse_path, class: 'btn btn-primary my-2' %>
        <% end %>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <% @horses.each do |horse| %>
          <div class="card m-2 mx-auto" style="width: 18rem;">
            <%= image_tag horse.image.url, class: "bd-placeholder-img card-img-top", size: "250" %>
            <div class="card-body">
              <h5 class="card-title "><%= horse.name %></h5>
              <p class="card-text m-1 small">品種：<%= horse.variety %></p>
              <p class="card-text m-1 small">性別：<%= horse.sex %></p>
              <p class="card-text m-1 small">毛色：<%= horse.color %></p>
              <p class="card-text m-1 small">生年月日：<%= horse.birthday.strftime('%Y年%m月%d日') %></p>
              <p class="card-text m-1 small">競走馬号名：<%= horse.race_name %></p>
              <p class="card-text m-1 small">入厩日：<%= horse.entry.strftime('%Y年%m月') %></p>
              <p class="card-text m-1 small"><%= horse.memo %></p>
            </div>
            <% if user_signed_in? && current_user.admin? %>
              <div class="card-body">
                <%= link_to '編集', edit_horse_path(horse), class: 'card-link btn btn-primary' %>
                <%= link_to '削除', horse_path(horse), class: 'card-link btn btn-primary', method: :delete %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/horses/new.html.erb
<div class="container mw-md">
  <%= form_for @horse do |f|%>
    <div class="form-group">
      <label class="control-label">名前</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">品種</label>
      <%= f.text_field :variety, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">性別</label>
      <%= f.text_field :sex, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">毛色</label>
      <%= f.text_field :color, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">競走馬名号</label>
      <%= f.text_field :race_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">生年月日</label>
      <%= f.date_field :birthday, class: "form-control"%>
    </div>
    <div class="form-group">
      <label  class="control-label">入厩日</label>
      <%= f.date_field :entry, class: "form-control"%>
    </div>
    <div class="form-group">
      <label  class="control-label">所属</label>
      <%= f.text_field :memo, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">写真</label><br>
      <button type="button" class="btn btn-outline-secondary rounded-pill">
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
      </button>
    </div>
    <div class="form-group">
      <%= f.submit '更新する', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/menus/edit.html.erb
<div class="container mw-md">
  <%= form_for @menu do |f|%>
    <div class="form-group">
      <label class="control-label">タイトル</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">金額</label>
      <%= f.number_field :money, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">所要時間</label>
      <%= f.number_field :time, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">内容</label>
      <%= f.text_area :memo, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">イメージ写真</label><br>
      <button type="button" class="btn btn-outline-secondary rounded-pill btn-block">
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: 'btn-block'%>
      </button>
    </div>
    <div class="form-group">
      <%= f.submit '更新する', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/menus/index.html.erb
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1>乗馬メニュー</h1>
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to '新規追加',new_menu_path, class: 'btn btn-primary my-2' %>
      <% end %>
    </div>
  </section>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
      <% @menus.each do |menu| %>
        <div class="card m-2">
          <div class="card-header bg-success text-light">
            <%= menu.title %>
          </div>
          <div class="card-body bg-light">
            <blockquote class="blockquote mb-0">
            <% if menu.image? %>
              <%= image_tag menu.image.url, class: "card-img-left mb-3", size: '320x200' %>
            <% else %>
              <%= image_tag "/assets/default.png", :size => '100x100' %>
            <% end %>
              <p class="small text-success"><%= simple_format(menu.memo) %></p>
              <footer class="blockquote-footer">所要時間：<cite title="Source Title"><%= menu.time%>分</cite></footer>
            </blockquote>
          </div>
          <% if user_signed_in? && current_user.admin? %>
            <div class="card-body">
              <%= link_to '編集', edit_menu_path(menu), class: 'card-link btn btn-primary' %>
              <%= link_to '削除', menu_path(menu), class: 'card-link btn btn-primary', method: :delete %>
            </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/menus/new.html.erb
<div class="container mw-md">
  <%= form_for @menu do |f|%>
    <div class="form-group">
      <label class="control-label">タイトル</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">金額</label>
      <%= f.number_field :money, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">所要時間</label>
      <%= f.number_field :time, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">内容</label>
      <%= f.text_area :memo, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">イメージ写真</label><br>
      <button type="button" class="btn btn-outline-secondary rounded-pill btn-block">
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: 'btn-block'%>
      </button>
    </div>
    <div class="form-group">
      <%= f.submit '登録する', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/news/new.html.erb
<div class="container mw-md">
  <%= form_for @news do |f|%>
    <div class="form-group">
      <label class="control-label">タイトル</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <label  class="control-label">内容</label>
      <%= f.text_area :content, size: "20x10", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit '投稿する', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/reservations/edit.html.erb
<div class="container mw-md">
  <div class="card">
    <div class="card-header">
      予約日時
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>  <%= @reservation.start_time.strftime('%Y/%m/%d %H:%M') %> 〜</p>
      </blockquote>
    </div>
  </div>
  <%= form_for @reservation do |f|%>
    <div class="form-group">
      <label class="control-label">乗馬メニュー</label>
      <%= f.collection_select :menu_id, Menu.all, :id, :title,{prompt: "選択してください"}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.submit '登録する', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/reservations/index.html.erb
<% if user_signed_in? && current_user.admin? %>
  <%= link_to '予約日登録', new_admin_reservation_path, class: "btn btn-primary btn-lg btn-block" %>
<% end %>
<%= month_calendar events: @reservations do |date, reservation| %>
  <%= date.day %>
  <div class="container d-flex flex-column">
      <div class="btn-group-vertical">
        <% if reservation.all?(&:reserved) %>
          <button type="button" class="btn btn-secondary btn-sm p-0">x</button>
        <% elsif reservation.select(&:reserved).size >= 3 %>
          <%= link_to '▲', reservation_path(date), class: 'btn btn-outline-primary btn-sm p-0'%>
        <% else%>
          <%= link_to '●', reservation_path(date), class: 'btn btn-outline-primary btn-sm p-0'%>
        <% end %>
      </div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<div class="container mw-md">
  <%= form_for @reservation do |f|%>

    <div class="form-group">
      <label class="control-label">乗馬メニュー</label>
      <%= f.collection_select :menu_id, @menus, :id, :title,{prompt: "選択してください"}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.submit '登録する', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/reservations/show.html.erb
<h1><%= params[:start_date] %></h1>
<% @reservations.each do |reservation| %>
  <% unless reservation.reserved?%>
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title"><%=link_to reservation.start_time.strftime("%H:%M"), edit_reservation_path(reservation), class: "card-text"%></h5>
      </div>
      <% if current_user.admin? %>
        <div class="card-footer text-muted">
          <%= link_to '削除', '#', class: "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title"><%=reservation.start_time.strftime("%H:%M")%>予約済み</h5>
      </div>
    </div>
  <% end %>
<% end %>